{% set name = "asyncer" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncer-{{ version }}.tar.gz
  sha256: 4734ede2bbe9c45caf8d81573af7a98d1bf866e3b92aa174b3f17b191cc51726

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.6,<4.0
    - anyio >=3.4.0,<4.0.0

test:
  imports:
    - asyncer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tiangolo/asyncer
  summary: Asyncer, async and await, focused on developer experience.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
