{% set name = "asyncer" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncer-{{ version }}.tar.gz
  sha256: d546c85f3626ebbaf06bb4395db49761c902a61a6ac802b1a74133cab4f7f433

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry-core
    - python >=3.6,<4.0
  run:
    - anyio >=3.4.0,<4.0.0
    - python >=3.6,<4.0

test:
  imports:
    - asyncer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tiangolo/asyncer
  summary: Asyncer, async and await, focused on developer experience.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
