{% set name = "asyncer" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asyncer-{{ version }}.tar.gz
  sha256: d9400418d4b508e5f3e819809bd3e7b9cd43d99a65c0a5eada14d41583164ca6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.0,<4.0.0
    - anyio >=3.4.0,<5.0
    - typing_extensions >=4.8.0,<5.0.0

test:
  imports:
    - asyncer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tiangolo/asyncer
  summary: Asyncer, async and await, focused on developer experience.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
